export const UI_TEXT = {
  login: {
    signIn: 'Log in',
    signUp: 'Sign up',
    toAccount: 'to your account',
    processing: 'Processing...',
    forgotPassword: 'Forgot password?',
    newToApp: 'New to RestJAM? 👉Sign Up👈 Now',
    alreadyRegistered: 'Already registered? 👉Login In👈 Now.',
    loginSignup: 'Login/Signup',
  },
  error: {
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc:
      "The page you're looking for doesn't exist. It might have been moved, deleted, or you entered the wrong URL.",
    goHome: 'Go Home',
    goBack: 'Go Back',
    needHelp: 'Need help? Contact our support team',
  },
  buttons: {
    getStarted: 'Get Started',
    logIn: 'Log In',
    signUp: 'Sign Up',
    signOut: 'Sign out',
    profile: 'Your Profile',
    google: 'Google',
    loading: 'Loading...',
    loadMore: 'Load More Posts',
    loadMoreResults: 'Load More Results',
    allLoaded: 'All Posts Loaded',
    allResultsLoaded: 'All Results Loaded',
    goToTop: 'Go to Top',
  },
  labels: {
    username: 'Username',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    phone: 'Phone',
    required: '*',
    title: 'Title',
    image: 'Pick an Image',
  },
  hero: {
    title: '"Discover. Taste. Share."',
    description:
      'Find the best spots, rate your favorites, and find your next favorite place.',
    button: 'Start with your account',
    buttonLoggedIn: 'Go to create a review',
    buttonLink: '/login',
    buttonLinkLoggedIn: '/create',
  },
  loginHero: {
    title: 'Welcome Back',
    description:
      "Welcome to RestJam! We're excited to have you here. Please log in or sign up to explore our vibrant community and discover amazing experiences.",
    button: 'Log in',
  },
  signupHero: {
    title: 'Signup',
    description:
      "Welcome to RestJam! We're excited to have you here. Please log in or sign up to explore our vibrant community and discover amazing experiences.",
    button: 'Log in',
  },
  detailHero: {
    title: 'Detail of the Spots',
    description:
      'Explore the best spots, rate your favorites, and find your next favorite place.',
  },
  createHero: {
    title: 'Create Your Review',
    description: '',
  },
  editHero: {
    title: 'Edit Your Review',
    description: '',
  },
  exploreHero: {
    title: 'Explore',
    description: 'Choose your filters and start exploring',
  },
  explore: {
    title: 'Explore',
    tagsTitle: 'Explore',
    tagsSubtitle: 'Tags',
    backButton: 'Back',
    searchPlaceholder: 'Explore restaurants, places, or tags...',
    searchContext: 'All the reviews/recommendations under',
    cleanFiltersButton: 'Clean Chosen Tags/Text',
    startExploringTitle: 'Start Exploring',
    startExploringDescription:
      'Search for restaurants, places, or tags to discover new experiences',
    searchingText: 'Searching for',
    searchErrorTitle: 'Search Error',
    noResultsTitle: 'No Results Found',
    noResultsDescription: 'Try adjusting your search terms or filters',
    placesDiscovered: 'places discovered',
    searchFor: 'for',
    moreButton: 'more',
    lessButton: 'less',
  },
  searchForm: {
    searchPlaceholder: 'Search restaurants, places, or tags...',
    mobileSearchPlaceholder: 'Search...',
  },
  donateHero: {
    title: 'Support Our Mission',
    description:
      'Your contributions help us maintain and improve our platform. Every donation counts!',
    button: 'Donate Now',
  },
  loading: {
    posts: 'Loading delicious reviews...',
    search: 'Searching for amazing places...',
    profile: 'Loading your profile...',
    detail: 'Loading post details...',
    creating: 'Creating your review...',
    updating: 'Updating your review...',
    component: 'Loading page...',
    tip: "💡 Pro tip: Use our filters to find exactly what you're craving!",
    tips: [
      "💡 Pro tip: Use our filters to find exactly what you're craving!",
      '🍴 Did you know? You can save posts to visit later!',
      '⭐ Rate restaurants to help others discover great places!',
      '📍 Add location tags to help others find nearby spots!',
      '📱 Our app works great on mobile devices too!',
    ],
  },
  loadingTypes: {
    COMPONENT: 'component',
    DATA: 'data',
    SEARCH: 'search',
    MINIMAL: 'minimal',
    FULL: 'full',
  },
  defaults: {
    userAvatar: 'https://img.daisyui.com/images/profile/demo/2@94.webp',
    userName: 'Anonymous User',
    authDelay: 100,
    emptyStateActionText: 'Share Your Experience',
  },
  dialogs: {
    deletePost: {
      type: 'delete',
      title: 'Delete Post',
      message: 'Are you sure you want to delete this restaurant post? This action cannot be undone and all associated data will be permanently removed.',
      confirmText: 'Delete Post',
      cancelText: 'Keep Post',
    },
    deletePostFromProfile: {
      type: 'delete',
      title: 'Delete Post',
      message: 'Are you sure you want to delete this post? This action cannot be undone.',
      confirmText: 'Delete Post',
      cancelText: 'Cancel',
    },
  },
}
